# Generated by Django 2.2.12 on 2021-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
