# Generated by Django 2.2.12 on 2021-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0002_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
